version: '3.1'

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: pg_isready
    container_name: postgres-container
    environment:
      POSTGRES_DB: alten_db
      POSTGRES_USER: alten
      PGUSER: alten
      POSTGRES_PASSWORD: alten
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
